### ISSUE TITLE
菜鸡小问下

### ISSUE THREAD

**Issue by jokerElsa** [newreport/vtbai#14]
大佬请教一下。
send2gpt方法中的
if tts_que.full():
      p.join()
是队列满了的时候阻塞用的。但是文件读写和请求api在rec2tts方法中应该也会有时延。（假设sleep 2s，来了10个十个弹幕，是否会开启10个进程/线程）
目前想到简单的解决方案是搞个无意义的helper_que。辅助记个数。

另：为了满足问答顺序我看代码是需要等答案回来才会塞问答。多线/进程操作同ttsque是否会乱序啊？我看testing里的testqueue是会乱序。

**Comment by newreport** [comment]
第一个问题 10个弹幕，得看[blivedm](https://github.com/xfgryujk/blivedm)的源码，应该用的是协程/线程开**10个线程（单核心）**，由于py的GIL锁存在，py要想**物理多核心多线程**运行只能开进程，不然只能在**物理单线程**上运行。
至于你说的tts队列满了来了10个弹幕，这个请求gpt阻塞我试的是不会影响弹幕线程，弹幕按照优先级/时间线满了的就出队了，现实场景是不可能也不会回答每条弹幕的。
第二个是不会乱序，testing里是我写功能测试的不做参考和应用无关，当时由于参考了其他库的方法，那个库里有这段话就cv过来了....，但是后面一想我这是队列不可能乱序的。
我本职是c#和go，py最近才学的，如有错误见谅。

**Comment by jokerElsa** [comment]
抱歉我py知识不是很好，多有叨扰。

那个。。。就是。。。我的意思是最开始就来了10个弹幕，然后都发送到gpt处理（假设都处理10秒钟）此时tts队列10秒中内都不是满的也不会走join阻塞。
而取出发送时已经将danmuque中的内容取出，从而会有更多的弹幕进来，导致10秒内创建很多进程？
这会不会导致10秒内如果弹幕很多，就会创建了好多进程。并且只有等前几个进程塞满tts队列了才开始阻塞

我一会找个弹幕多的直播试下。

**Comment by newreport** [comment]
好像确实有问题...，我改下，tts满了应该不再请求openai

弹幕不会创建进程，b站抓取直播流用的是websocket，始终在一个线程内，满了就踢出弹幕队列的旧弹幕，目的是回答时间线较新的。进程只有在
```python
 p = multiprocessing.Process(target=rec2tts, args=())
 p.start()
```
才会创建，即请求openai时创建

**Comment by jokerElsa** [comment]
> 好像确实有问题...，我改下，tts满了应该不再请求openai
> 
> 弹幕不会创建进程，b站抓取直播流用的是websocket，始终在一个线程内，满了就踢出弹幕队列的旧弹幕，目的是回答时间线较新的。进程只有在
> 
> ```python
>  p = multiprocessing.Process(target=rec2tts, args=())
>  p.start()
> ```
> 
> 才会创建，即请求openai时创建

是的 弹幕不会，弹幕塞满了你会抛弃队列中老的，但是sendgpt方法是自循环的会实时取danmuque中的内容并开进程，阻塞在进程内（文件写入，gpt请求，tts队列写入），然后弹幕一看又能塞了就继续塞，sendgpt发现能开了就继续开，直到前几个进程处理完塞满tts，然后queue.put阻塞所有开启的进程。
我开始以为只是刚开始的并发会开很多，但是现在想想好像是反复的，只要ttsque.full()没阻塞到。这个时间段内容就一直开进程。

不知道我理解的对不对。
