### ISSUE TITLE
# 弹幕，将 resource 中的 hmtl 拖到 obs 里，为什么我obs里什么都没显示

### ISSUE THREAD

**Issue by zlazlazl** [newreport/vtbai#16]

**Comment by newreport** [comment]
python后台起了吗，监听的房间有弹幕吗

**Comment by zlazlazl** [comment]
> python后台起了吗，监听的房间有弹幕吗

我直接打开html文件能看到文字，但是html拖进OBS，OBS里不显示

**Comment by newreport** [comment]
obs里，添加——浏览器——新建——本地文件，选中html

**Comment by zlazlazl** [comment]
> obs里，添加——浏览器——新建——本地文件，选中html

我解决方法是，通过obs-websocket，实时输出到obs中，没有通过html了

**Comment by newreport** [comment]
> > obs里，添加——浏览器——新建——本地文件，选中html
> 
> 我解决方法是，通过obs-websocket，实时输出到obs中，没有通过html了

嗯对，实时websocket最好，另一个docker分支正在这样弄，api图省事效率差
